# Stage 1: Build the frontend
FROM node:20-alpine AS frontend_builder

WORKDIR /app

COPY ./frontend/package*.json ./

RUN npm install

COPY ./frontend /app

RUN npm run build

# Stage 2: Build the backend
FROM node:20-alpine

WORKDIR /app

COPY ./backend/package*.json ./

RUN npm install

COPY ./backend /app

COPY --from=frontend_builder /app/dist /app/public

# --from=frontend_builder /app/dist /app/public how does this work? it copies the dist folder from the frontend_builder stage to the public folder in the backend stage. This allows the backend server to serve the built frontend files.

CMD ["node", "server.js"]